#!/bin/bash
set -e

# Get rid of existing binaries
rm -f kcompose*
rm -rf Godeps/_workspace/pkg

go generate

BUILDTIME=$(date --rfc-3339 ns | sed -e 's/ /T/') &> /dev/null
GITCOMMIT=$(git rev-parse --short HEAD)

# Build binaries
gox "${OS_PLATFORM_ARG[@]}" "${OS_ARCH_ARG[@]}" \
    -output="bundles/kcompose_{{.OS}}-{{.Arch}}/kompose" \
    -ldflags="-w -X github.com/docker/libcompose/version.GITCOMMIT=${GITCOMMIT} -X github.com/docker/libcompose/version.BUILDTIME=${BUILDTIME}" \
    ./cli/main
